baseURL = "/"
languageCode = "en-us"
title = "XR VisionDevCamp Fukuoka 2026 – Proposal"
theme = "reveal-hugo"
disableKinds = ["sitemap", "RSS", "taxonomy", "term"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params]
author = "VisionDevCamp"

[params.reveal_hugo]
theme = "black"
history = true
slide_number = true
transition = "slide"
transition_speed = "default"
margin = 0.1
